name: blog
description: Erakomp's Blog Application
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  carousel_slider: ^2.1.0
  google_fonts: ^1.1.0
  background_app_bar: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lorem: ^1.1.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/